// Entreprises Cybersécurité France - Partie 1: Pure Players Cyber & Startups (1-100)
const DATA_PART1 = [
{n:"Orange Cyberdefense",c:"Pure Player Cyber",v:"Paris",t:"GE",s:"orange-cyberdefense.com",sp:["SOC","Pentest","Audit","Consulting","CERT"],sr:"LinkedIn, Indeed, WTTJ"},
{n:"Wavestone",c:"Big4 / Cabinet Conseil",v:"Paris",t:"ETI",s:"wavestone.com",sp:["Conseil","GRC","Audit","Stratégie cyber"],sr:"LinkedIn, WTTJ"},
{n:"Thales (Cybersecurity)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"thalesgroup.com",sp:["Défense","Chiffrement","IAM","SOC"],sr:"LinkedIn, Indeed"},
{n:"Capgemini (Cybersecurity)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"capgemini.com",sp:["Consulting","SOC","Cloud Security","IAM"],sr:"LinkedIn, Indeed, WTTJ"},
{n:"Sopra Steria",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"soprasteria.com",sp:["Consulting","IAM","SOC","Intégration"],sr:"LinkedIn, Indeed"},
{n:"Atos (Eviden)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"atos.net",sp:["SOC","Cloud Security","IAM","Big Data Security"],sr:"LinkedIn, Indeed"},
{n:"Accenture Security",c:"Big4 / Cabinet Conseil",v:"Paris",t:"GE",s:"accenture.com",sp:["Consulting","Strategy","Managed Security"],sr:"LinkedIn, WTTJ"},
{n:"Deloitte Cyber",c:"Big4 / Cabinet Conseil",v:"Paris",t:"GE",s:"deloitte.com",sp:["Audit","Conseil","GRC","Forensics"],sr:"LinkedIn, Indeed"},
{n:"EY Cybersecurity",c:"Big4 / Cabinet Conseil",v:"Paris",t:"GE",s:"ey.com",sp:["Audit","GRC","Conseil","Privacy"],sr:"LinkedIn, Indeed"},
{n:"KPMG Cyber",c:"Big4 / Cabinet Conseil",v:"Paris",t:"GE",s:"kpmg.fr",sp:["Audit","Conseil","GRC","Cloud Security"],sr:"LinkedIn, Indeed"},
{n:"PwC Cyber",c:"Big4 / Cabinet Conseil",v:"Paris",t:"GE",s:"pwc.fr",sp:["Conseil","Audit","Forensics","Privacy"],sr:"LinkedIn, Indeed"},
{n:"Devoteam",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"devoteam.com",sp:["Consulting","Cloud Security","IAM","GRC"],sr:"LinkedIn, Indeed, WTTJ"},
{n:"CGI France",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"cgi.com",sp:["Consulting","SOC","IAM","Intégration"],sr:"LinkedIn, Indeed"},
{n:"Sogeti (Capgemini)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"sogeti.com",sp:["Testing","Audit","Cloud Security"],sr:"LinkedIn, Indeed"},
{n:"Inetum",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"inetum.com",sp:["Consulting","IAM","SOC","Intégration"],sr:"LinkedIn, Indeed"},
{n:"Synacktiv",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"synacktiv.com",sp:["Pentest","Red Team","Reverse","R&D"],sr:"LinkedIn, WTTJ"},
{n:"Intrinsec",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"intrinsec.com",sp:["SOC","CERT","Pentest","CTI","Consulting"],sr:"LinkedIn, WTTJ"},
{n:"I-Tracing",c:"Pure Player Cyber",v:"Paris",t:"ETI",s:"i-tracing.com",sp:["SOC","SIEM","IAM","Cloud Security"],sr:"LinkedIn, Indeed"},
{n:"Advens",c:"Pure Player Cyber",v:"Lille",t:"ETI",s:"advens.fr",sp:["SOC","Pentest","Consulting","GRC"],sr:"LinkedIn, Indeed, WTTJ"},
{n:"Formind",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"formind.fr",sp:["Consulting","GRC","Audit","Intégration"],sr:"LinkedIn, WTTJ"},
{n:"Synetis",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"synetis.com",sp:["IAM","SOC","Audit","Consulting"],sr:"LinkedIn, WTTJ"},
{n:"Almond (ex-Amossys)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"almond.consulting",sp:["Audit","Pentest","GRC","SOC"],sr:"LinkedIn, WTTJ"},
{n:"Sekoia.io",c:"Startup Cyber",v:"Paris",t:"PME",s:"sekoia.io",sp:["XDR","CTI","SOC","Detection"],sr:"LinkedIn, WTTJ"},
{n:"HarfangLab",c:"Startup Cyber",v:"Paris",t:"PME",s:"harfanglab.io",sp:["EDR","Detection","Response","IA"],sr:"LinkedIn, WTTJ"},
{n:"TEHTRIS",c:"Startup Cyber",v:"Bordeaux",t:"PME",s:"tehtris.com",sp:["XDR","EDR","SIEM","Deception"],sr:"LinkedIn, WTTJ"},
{n:"CybelAngel",c:"Startup Cyber",v:"Paris",t:"PME",s:"cybelangel.com",sp:["Threat Intelligence","EASM","Data Leak"],sr:"LinkedIn, WTTJ"},
{n:"Gatewatcher",c:"Startup Cyber",v:"Paris",t:"PME",s:"gatewatcher.com",sp:["NDR","Detection","Network Security"],sr:"LinkedIn, WTTJ"},
{n:"YesWeHack",c:"Startup Cyber",v:"Paris",t:"PME",s:"yeswehack.com",sp:["Bug Bounty","VDP","Pentest"],sr:"LinkedIn, WTTJ"},
{n:"Yogosha",c:"Startup Cyber",v:"Paris",t:"PME",s:"yogosha.com",sp:["Bug Bounty","Pentest","Offensive Security"],sr:"LinkedIn, WTTJ"},
{n:"DataDome",c:"Startup Cyber",v:"Paris",t:"PME",s:"datadome.co",sp:["Bot Protection","Fraud","API Security"],sr:"LinkedIn, WTTJ"},
{n:"Stormshield",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"stormshield.com",sp:["Firewall","Network Security","Endpoint"],sr:"LinkedIn, Indeed"},
{n:"Wallix",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"wallix.com",sp:["PAM","IAM","Access Management"],sr:"LinkedIn, WTTJ"},
{n:"Mailinblack",c:"Éditeur / Solutions",v:"Marseille",t:"PME",s:"mailinblack.com",sp:["Email Security","Phishing","Awareness"],sr:"LinkedIn, WTTJ"},
{n:"Vade (Hornetsecurity)",c:"Éditeur / Solutions",v:"Lille",t:"PME",s:"vadesecure.com",sp:["Email Security","Phishing","IA"],sr:"LinkedIn, Indeed"},
{n:"Oodrive",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"oodrive.com",sp:["Cloud sécurisé","Signature","Partage"],sr:"LinkedIn, WTTJ"},
{n:"Pradeo",c:"Startup Cyber",v:"Montpellier",t:"PME",s:"pradeo.com",sp:["Mobile Security","App Security"],sr:"LinkedIn, WTTJ"},
{n:"CrowdSec",c:"Startup Cyber",v:"Paris",t:"PME",s:"crowdsec.net",sp:["Open Source","IDS","Threat Intel"],sr:"LinkedIn, WTTJ"},
{n:"Alsid (Tenable)",c:"Startup Cyber",v:"Paris",t:"PME",s:"alsid.com",sp:["Active Directory","IAM Security"],sr:"LinkedIn"},
{n:"Qevlar AI",c:"Startup Cyber",v:"Paris",t:"TPE",s:"qevlar.com",sp:["IA","SOC Automation","Detection"],sr:"WTTJ"},
{n:"Filigran",c:"Startup Cyber",v:"Paris",t:"PME",s:"filigran.io",sp:["CTI","OpenCTI","Threat Intel Platform"],sr:"LinkedIn, WTTJ"},
{n:"Glimps",c:"Startup Cyber",v:"Rennes",t:"TPE",s:"glimps.fr",sp:["Malware Analysis","IA","Detection"],sr:"LinkedIn, WTTJ"},
{n:"SnowPack",c:"Startup Cyber",v:"Paris",t:"TPE",s:"snowpack.eu",sp:["Network Privacy","Stealth","Zero Trust"],sr:"LinkedIn"},
{n:"Cyberwatch",c:"Startup Cyber",v:"Paris",t:"PME",s:"cyberwatch.fr",sp:["Vulnerability Management","Compliance"],sr:"LinkedIn, WTTJ"},
{n:"Vaadata",c:"Pure Player Cyber",v:"Lyon",t:"PME",s:"vaadata.com",sp:["Pentest","Audit","Web Security"],sr:"LinkedIn, WTTJ"},
{n:"AlgoSecure",c:"Pure Player Cyber",v:"Lyon",t:"PME",s:"algosecure.fr",sp:["Pentest","Audit","Consulting","GRC"],sr:"LinkedIn, WTTJ"},
{n:"Holiseum",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"holiseum.com",sp:["OT Security","Consulting","Audit"],sr:"LinkedIn, WTTJ"},
{n:"Akerva",c:"Pure Player Cyber",v:"Rennes",t:"PME",s:"akerva.com",sp:["Audit","Pentest","Consulting","Formation"],sr:"LinkedIn, WTTJ"},
{n:"XMCO",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"xmco.fr",sp:["Pentest","Audit","Veille","CTI"],sr:"LinkedIn, WTTJ"},
{n:"Conix (Atos)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"conix.fr",sp:["SOC","CERT","Pentest"],sr:"LinkedIn"},
{n:"NES (Network Engineering & Security)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"nes.fr",sp:["Consulting","Intégration","SOC"],sr:"LinkedIn, Indeed"},
{n:"Claranet Cyber Security",c:"Pure Player Cyber",v:"Paris",t:"ETI",s:"claranet.com",sp:["Pentest","Red Team","Managed Security"],sr:"LinkedIn, WTTJ"},
{n:"SysDream (Hub One)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"sysdream.com",sp:["Pentest","Formation","Red Team"],sr:"LinkedIn"},
{n:"OnePoint",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"groupeonepoint.com",sp:["Consulting","Cyber Strategy","Cloud"],sr:"LinkedIn, WTTJ"},
{n:"Econocom",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"econocom.com",sp:["Infra","Sécurité","Digital Workplace"],sr:"LinkedIn, Indeed"},
{n:"Exaprobe (Econocom)",c:"Intégrateur / MSSP",v:"Lyon",t:"PME",s:"exaprobe.com",sp:["Intégration","Network Security","SOC"],sr:"LinkedIn"},
{n:"Nomios",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"nomios.com",sp:["Intégration","Network Security","Firewall"],sr:"LinkedIn, Indeed"},
{n:"Neurones",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"neurones.net",sp:["Infra","Sécurité","Cloud","IAM"],sr:"LinkedIn, Indeed"},
{n:"Digitemis",c:"Pure Player Cyber",v:"Nantes",t:"PME",s:"digitemis.com",sp:["Pentest","Audit","DPO","RGPD"],sr:"LinkedIn, WTTJ"},
{n:"Netsecure (Metsys)",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"metsys.fr",sp:["IAM","Microsoft Security","Cloud"],sr:"LinkedIn"},
{n:"Opfor Intelligence",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"opfor-intelligence.fr",sp:["Red Team","Pentest","OSINT"],sr:"LinkedIn"},
{n:"Quarkslab",c:"Startup Cyber",v:"Paris",t:"PME",s:"quarkslab.com",sp:["Reverse Engineering","Obfuscation","R&D"],sr:"LinkedIn, WTTJ"},
{n:"Lexfo (Orange)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"lexfo.fr",sp:["Pentest","Audit","Forensics"],sr:"LinkedIn"},
{n:"Wavely (ex-ITrust)",c:"Startup Cyber",v:"Toulouse",t:"PME",s:"itrust.fr",sp:["SOC","SIEM","Vulnerability Scanner"],sr:"LinkedIn, WTTJ"},
{n:"Cyberens",c:"Pure Player Cyber",v:"Bordeaux",t:"PME",s:"cyberens.fr",sp:["Consulting","Audit","Défense"],sr:"LinkedIn"},
{n:"Steef",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"steef.fr",sp:["Consulting","DevSecOps","Cloud Security"],sr:"LinkedIn, WTTJ"},
{n:"Fidens (TVH Consulting)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"fidens.fr",sp:["GRC","ISO 27001","Consulting"],sr:"LinkedIn"},
{n:"Manika",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"manika.fr",sp:["IAM","Consulting","Intégration"],sr:"LinkedIn, WTTJ"},
{n:"Serma Safety & Security",c:"Pure Player Cyber",v:"Bordeaux",t:"PME",s:"serma.com",sp:["Hardware Security","IoT","Embedded"],sr:"LinkedIn"},
{n:"Amossys",c:"Pure Player Cyber",v:"Rennes",t:"PME",s:"amossys.fr",sp:["R&D","Pentest","Simulation"],sr:"LinkedIn"},
{n:"Airbus CyberSecurity",c:"Entreprise avec équipe cyber",v:"Toulouse",t:"GE",s:"airbus.com",sp:["SOC","CERT","OT Security","Défense"],sr:"LinkedIn, Indeed"},
{n:"Safran (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"safran-group.com",sp:["OT Security","IAM","SOC"],sr:"LinkedIn, Indeed"},
{n:"Naval Group (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"naval-group.com",sp:["OT Security","Défense","SOC"],sr:"LinkedIn"},
{n:"Dassault Systèmes (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"3ds.com",sp:["Product Security","Cloud","IAM"],sr:"LinkedIn"},
{n:"Engie (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"engie.com",sp:["OT Security","SOC","GRC"],sr:"LinkedIn, Indeed"},
{n:"EDF (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"edf.fr",sp:["OT Security","SOC","SCADA"],sr:"LinkedIn, Indeed"},
{n:"TotalEnergies (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"totalenergies.com",sp:["OT Security","SOC","Cloud Security"],sr:"LinkedIn, Indeed"},
{n:"BNP Paribas (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"bnpparibas.com",sp:["SOC","Fraud","IAM","GRC"],sr:"LinkedIn, Indeed"},
{n:"Société Générale (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"societegenerale.com",sp:["SOC","Red Team","IAM","Fraud"],sr:"LinkedIn, Indeed"},
{n:"Crédit Agricole (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"credit-agricole.com",sp:["SOC","IAM","Fraud","GRC"],sr:"LinkedIn, Indeed"},
{n:"AXA (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"axa.com",sp:["SOC","Cloud Security","GRC"],sr:"LinkedIn, Indeed"},
{n:"Renault (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"renaultgroup.com",sp:["OT Security","SOC","IAM"],sr:"LinkedIn, Indeed"},
{n:"L'Oréal (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"loreal.com",sp:["Cloud Security","IAM","GRC"],sr:"LinkedIn"},
{n:"Sanofi (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"sanofi.com",sp:["Pharma Security","SOC","Cloud"],sr:"LinkedIn, Indeed"},
{n:"Schneider Electric (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"se.com",sp:["OT Security","IoT","SCADA"],sr:"LinkedIn, Indeed"},
{n:"Saint-Gobain (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"saint-gobain.com",sp:["SOC","Incident Response","GRC"],sr:"LinkedIn"},
{n:"Bouygues Telecom (Cyber)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"bouyguestelecom.fr",sp:["SOC","Network Security","Cloud"],sr:"LinkedIn, Indeed"},
{n:"SFR Business (Cyber)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"sfrbusiness.fr",sp:["SOC","MSSP","Network Security"],sr:"LinkedIn, Indeed"},
{n:"OVHcloud (Security)",c:"Telecom / Cloud",v:"Roubaix",t:"ETI",s:"ovhcloud.com",sp:["Cloud Security","DDoS","Infra"],sr:"LinkedIn, WTTJ"},
{n:"Scaleway (Security)",c:"Telecom / Cloud",v:"Paris",t:"PME",s:"scaleway.com",sp:["Cloud Security","Infra","IAM"],sr:"LinkedIn, WTTJ"},
{n:"Free / Iliad (Cyber)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"iliad.fr",sp:["Network Security","SOC","Infra"],sr:"LinkedIn"},
{n:"Docaposte (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"docaposte.com",sp:["Cloud souverain","IAM","Signature"],sr:"LinkedIn, WTTJ"},
{n:"Orsenna",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"orsenna.fr",sp:["Intégration","IAM","Sécurité réseau"],sr:"LinkedIn"},
{n:"e-Xpert Solutions",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"e-xpertsolutions.com",sp:["WAF","IAM","Network Security"],sr:"LinkedIn"},
{n:"Sys Advisor (BDO)",c:"Pure Player Cyber",v:"Lyon",t:"PME",s:"sysadvisor.com",sp:["Audit","Consulting","GRC"],sr:"LinkedIn"},
{n:"ISE Systems",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"ise-systems.com",sp:["SOC","Intégration","MSSP"],sr:"LinkedIn"},
{n:"Metsys",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"metsys.fr",sp:["Microsoft Security","IAM","Cloud"],sr:"LinkedIn, WTTJ"},
{n:"NetXP",c:"Intégrateur / MSSP",v:"Lyon",t:"PME",s:"netxp.fr",sp:["Intégration","Firewall","SOC"],sr:"LinkedIn"},
{n:"Apixit",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"apixit.fr",sp:["Network","Cybersecurity","SD-WAN"],sr:"LinkedIn"},
{n:"NSI (Nanyang SI)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"nsi.fr",sp:["Consulting","Intégration","IAM"],sr:"LinkedIn"},
{n:"Micropole",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"micropole.com",sp:["Data Security","Cloud","Consulting"],sr:"LinkedIn"},
{n:"Altran (Capgemini Engineering)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"capgemini.com",sp:["OT Security","IoT","Consulting"],sr:"LinkedIn, Indeed"},
{n:"Alten",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"alten.com",sp:["Consulting","OT Security","Défense"],sr:"LinkedIn, Indeed"},
{n:"Assystem",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"assystem.com",sp:["Nuclear Security","OT","Consulting"],sr:"LinkedIn"},
];
