// Entreprises Cybersécurité France - Partie 4 (301-400)
const DATA_PART4 = [
{n:"Leboncoin (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"leboncoin.fr",sp:["AppSec","Fraud","Bug Bounty"],sr:"LinkedIn, WTTJ"},
{n:"Doctolib (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"doctolib.fr",sp:["AppSec","Privacy","Cloud"],sr:"LinkedIn, WTTJ"},
{n:"BlaBlaCar (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"blablacar.com",sp:["AppSec","Cloud","Privacy"],sr:"LinkedIn, WTTJ"},
{n:"ManoMano (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"manomano.fr",sp:["AppSec","Cloud","Fraud"],sr:"LinkedIn, WTTJ"},
{n:"Back Market (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"backmarket.com",sp:["AppSec","Cloud","Fraud"],sr:"LinkedIn, WTTJ"},
{n:"Vestiaire Collective (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"vestiairecollective.com",sp:["AppSec","Fraud","Privacy"],sr:"LinkedIn"},
{n:"Qonto (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"qonto.com",sp:["FinSec","Cloud","Fraud","PCI"],sr:"LinkedIn, WTTJ"},
{n:"Lydia (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"lydia-app.com",sp:["FinSec","Mobile","Fraud"],sr:"LinkedIn, WTTJ"},
{n:"Alan (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"alan.com",sp:["HealthSec","Cloud","Privacy"],sr:"LinkedIn, WTTJ"},
{n:"Swile (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"swile.co",sp:["FinSec","AppSec","Cloud"],sr:"LinkedIn, WTTJ"},
{n:"Ledger",c:"Startup Cyber",v:"Paris",t:"ETI",s:"ledger.com",sp:["Blockchain Security","Hardware Wallet","Crypto"],sr:"LinkedIn, WTTJ"},
{n:"Ledger Donjon",c:"Startup Cyber",v:"Paris",t:"ETI",s:"donjon.ledger.com",sp:["Hardware Security","Side Channel","Research"],sr:"LinkedIn"},
{n:"Shift Technology (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"shift-technology.com",sp:["Fraud Detection","IA","Insurance"],sr:"LinkedIn, WTTJ"},
{n:"Mirakl (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"mirakl.com",sp:["Platform Security","AppSec","Cloud"],sr:"LinkedIn, WTTJ"},
{n:"ContentSquare (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"contentsquare.com",sp:["Privacy","Cloud Security","AppSec"],sr:"LinkedIn, WTTJ"},
{n:"Dataiku (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"dataiku.com",sp:["Data Security","ML Security","Cloud"],sr:"LinkedIn, WTTJ"},
{n:"Talend (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"talend.com",sp:["Data Security","Cloud","Compliance"],sr:"LinkedIn"},
{n:"OVH (SOC interne)",c:"Telecom / Cloud",v:"Roubaix",t:"ETI",s:"ovhcloud.com",sp:["Anti-DDoS","SOC","Incident Response"],sr:"LinkedIn, WTTJ"},
{n:"Ivalua (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"ivalua.com",sp:["SaaS Security","Cloud","AppSec"],sr:"LinkedIn"},
{n:"Murex (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"murex.com",sp:["FinSec","AppSec","Infra"],sr:"LinkedIn"},
{n:"Amadeus France (Security)",c:"Entreprise avec équipe cyber",v:"Nice",t:"GE",s:"amadeus.com",sp:["Travel Security","AppSec","Cloud"],sr:"LinkedIn"},
{n:"Dassault Systèmes (3DS) Cyber",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"3ds.com",sp:["Cloud Security","Product Security"],sr:"LinkedIn"},
{n:"Schneider Electric (Cyber interne)",c:"Entreprise avec équipe cyber",v:"Grenoble",t:"GE",s:"se.com",sp:["Product Security","OT","IoT"],sr:"LinkedIn, Indeed"},
{n:"Alstom (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"alstom.com",sp:["Rail Security","OT","SCADA"],sr:"LinkedIn"},
{n:"Framatome (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"framatome.com",sp:["Nuclear Security","OT","SCADA"],sr:"LinkedIn"},
{n:"CEA (Cyber)",c:"Entreprise avec équipe cyber",v:"Grenoble",t:"GE",s:"cea.fr",sp:["Research","Crypto","Hardware"],sr:"LinkedIn"},
{n:"Safran Electronics & Defense",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"safran-group.com",sp:["Défense","Embedded Security","Crypto"],sr:"LinkedIn"},
{n:"Groupe SEB (Cyber)",c:"Entreprise avec équipe cyber",v:"Lyon",t:"GE",s:"groupeseb.com",sp:["IoT Security","Cloud","OT"],sr:"LinkedIn"},
{n:"La Banque Postale (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"labanquepostale.fr",sp:["FinSec","SOC","Fraud"],sr:"LinkedIn, Indeed"},
{n:"BPCE / Natixis (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"groupebpce.com",sp:["FinSec","SOC","Fraud","IAM"],sr:"LinkedIn, Indeed"},
{n:"Groupama (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"groupama.com",sp:["SOC","GRC","Assurance"],sr:"LinkedIn"},
{n:"Covéa / MAIF / MACIF (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"covea.eu",sp:["SOC","GRC","Cloud"],sr:"LinkedIn"},
{n:"AG2R La Mondiale (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"ag2rlamondiale.fr",sp:["SOC","IAM","GRC"],sr:"LinkedIn"},
{n:"Malakoff Humanis (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"malakoffhumanis.com",sp:["SOC","Cloud","GRC"],sr:"LinkedIn"},
{n:"Allianz France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"allianz.fr",sp:["SOC","Fraud","GRC"],sr:"LinkedIn"},
{n:"Generali France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"generali.fr",sp:["SOC","GRC","Cloud"],sr:"LinkedIn"},
{n:"CNP Assurances (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"cnp.fr",sp:["SOC","IAM","Cloud"],sr:"LinkedIn"},
{n:"Crédit Mutuel (Cyber)",c:"Entreprise avec équipe cyber",v:"Strasbourg",t:"GE",s:"creditmutuel.fr",sp:["FinSec","SOC","Fraud"],sr:"LinkedIn"},
{n:"LCL (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"lcl.fr",sp:["FinSec","SOC","Fraud"],sr:"LinkedIn"},
{n:"CIC (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"cic.fr",sp:["FinSec","SOC","Fraud"],sr:"LinkedIn"},
{n:"Boursorama (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"boursorama.com",sp:["FinSec","AppSec","Fraud"],sr:"LinkedIn"},
{n:"Fortuneo (Cyber)",c:"Entreprise avec équipe cyber",v:"Rennes",t:"PME",s:"fortuneo.fr",sp:["FinSec","AppSec","Fraud"],sr:"LinkedIn"},
{n:"Oney (Cyber)",c:"Entreprise avec équipe cyber",v:"Lille",t:"ETI",s:"oney.com",sp:["FinSec","Fraud","PCI"],sr:"LinkedIn"},
{n:"Arkéa (Cyber)",c:"Entreprise avec équipe cyber",v:"Rennes",t:"GE",s:"arkea.com",sp:["FinSec","SOC","IAM"],sr:"LinkedIn"},
{n:"HSBC France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"hsbc.fr",sp:["FinSec","SOC","GRC"],sr:"LinkedIn"},
{n:"Lazard France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"lazard.com",sp:["FinSec","Data Protection"],sr:"LinkedIn"},
{n:"Natixis (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"natixis.com",sp:["FinSec","SOC","Fraud","Red Team"],sr:"LinkedIn, Indeed"},
{n:"Euronext (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"euronext.com",sp:["FinSec","Trading Security","SOC"],sr:"LinkedIn"},
{n:"Treezor (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"treezor.com",sp:["FinSec","PCI","API Security"],sr:"LinkedIn, WTTJ"},
{n:"Spendesk (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"spendesk.com",sp:["FinSec","AppSec","Cloud"],sr:"LinkedIn, WTTJ"},
{n:"Pennylane (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"pennylane.com",sp:["FinSec","Cloud","AppSec"],sr:"LinkedIn, WTTJ"},
{n:"Younited Credit (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"younited-credit.com",sp:["FinSec","Cloud","Fraud"],sr:"LinkedIn"},
{n:"Luko / Leocare (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"luko.eu",sp:["InsurTech","Cloud","AppSec"],sr:"LinkedIn"},
{n:"PayFit (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"payfit.com",sp:["SaaS Security","Cloud","Privacy"],sr:"LinkedIn, WTTJ"},
{n:"Withings (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"withings.com",sp:["IoT Security","Health","Privacy"],sr:"LinkedIn, WTTJ"},
{n:"Parrot (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"parrot.com",sp:["Drone Security","Embedded","Defence"],sr:"LinkedIn"},
{n:"Devialet (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"devialet.com",sp:["IoT Security","Embedded"],sr:"LinkedIn"},
{n:"Sigfox (Security)",c:"Entreprise avec équipe cyber",v:"Toulouse",t:"PME",s:"music.sigfox.com",sp:["IoT Security","Network","LPWAN"],sr:"LinkedIn"},
{n:"Actia (Cyber)",c:"Entreprise avec équipe cyber",v:"Toulouse",t:"ETI",s:"actia.com",sp:["Automotive Security","OT","Embedded"],sr:"LinkedIn"},
{n:"Nexans (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"nexans.com",sp:["OT Security","Industrie","SOC"],sr:"LinkedIn"},
{n:"Peugeot / Stellantis (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"stellantis.com",sp:["Automotive Security","Connected Car"],sr:"LinkedIn"},
{n:"Plastic Omnium (Cyber)",c:"Entreprise avec équipe cyber",v:"Lyon",t:"GE",s:"plasticomnium.com",sp:["OT Security","Automotive"],sr:"LinkedIn"},
{n:"Safran Aircraft Engines (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"safran-group.com",sp:["OT Security","Aviation","Embedded"],sr:"LinkedIn"},
{n:"Zodiac Aerospace (Safran) Cyber",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"safran-group.com",sp:["Aviation Security","Embedded"],sr:"LinkedIn"},
{n:"Ariane Group (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"ariane.group",sp:["Space Security","OT","Défense"],sr:"LinkedIn"},
{n:"CNES (Cyber)",c:"Entreprise avec équipe cyber",v:"Toulouse",t:"GE",s:"cnes.fr",sp:["Space Security","Satellite","OT"],sr:"LinkedIn"},
{n:"Eurocontrol France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"eurocontrol.int",sp:["Aviation Security","OT"],sr:"LinkedIn"},
{n:"Ingenico (Worldline) Cyber",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"ingenico.com",sp:["Payment Security","PCI","Embedded"],sr:"LinkedIn"},
{n:"Oberthur Technologies (Idemia)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"idemia.com",sp:["Smart Card","PKI","Embedded"],sr:"LinkedIn"},
{n:"Lex Persona",c:"Startup Cyber",v:"Paris",t:"TPE",s:"lex-persona.com",sp:["E-signature","Trust Services"],sr:"LinkedIn"},
{n:"Cryptosense",c:"Startup Cyber",v:"Paris",t:"TPE",s:"cryptosense.com",sp:["Cryptography","PKI","Analysis"],sr:"LinkedIn"},
{n:"CryptoExperts",c:"Startup Cyber",v:"Paris",t:"TPE",s:"cryptoexperts.com",sp:["Cryptography","Research","Consulting"],sr:"LinkedIn"},
{n:"Cosmian",c:"Startup Cyber",v:"Paris",t:"TPE",s:"cosmian.com",sp:["Encryption","Confidential Computing"],sr:"LinkedIn, WTTJ"},
{n:"Zama",c:"Startup Cyber",v:"Paris",t:"TPE",s:"zama.ai",sp:["FHE","Homomorphic Encryption","Privacy"],sr:"LinkedIn, WTTJ"},
{n:"Inpher France",c:"Startup Cyber",v:"Paris",t:"TPE",s:"inpher.io",sp:["Privacy","Confidential Computing"],sr:"LinkedIn"},
{n:"Evina",c:"Startup Cyber",v:"Paris",t:"PME",s:"evina.com",sp:["Mobile Fraud","DCB Security"],sr:"LinkedIn, WTTJ"},
{n:"Verimatrix France",c:"Éditeur / Solutions",v:"Nice",t:"ETI",s:"verimatrix.com",sp:["App Security","DRM","Content Protection"],sr:"LinkedIn"},
{n:"Atempo (Security)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"atempo.com",sp:["Backup","Archiving","Ransomware"],sr:"LinkedIn"},
{n:"Wooxo",c:"Éditeur / Solutions",v:"Lyon",t:"PME",s:"wooxo.fr",sp:["Backup","PRA","Ransomware Protection"],sr:"LinkedIn"},
{n:"Nucleon Security",c:"Startup Cyber",v:"Rennes",t:"TPE",s:"nucleon-security.com",sp:["EDR","Detection","IA"],sr:"LinkedIn"},
{n:"Sesame IT",c:"Startup Cyber",v:"Paris",t:"TPE",s:"sesameit.com",sp:["NDR","Network Detection"],sr:"LinkedIn"},
{n:"Board of Cyber",c:"Startup Cyber",v:"Paris",t:"TPE",s:"music.boardofcyber.io",sp:["Cyber Rating","Risk Assessment"],sr:"LinkedIn, WTTJ"},
{n:"Trustpair",c:"Startup Cyber",v:"Paris",t:"PME",s:"trustpair.com",sp:["Fraud Prevention","B2B Payments"],sr:"LinkedIn, WTTJ"},
{n:"Sis ID",c:"Startup Cyber",v:"Lyon",t:"PME",s:"sisid.com",sp:["Fraud Prevention","Identity Verification"],sr:"LinkedIn"},
{n:"Vaultinum",c:"Startup Cyber",v:"Paris",t:"TPE",s:"vaultinum.com",sp:["Software Escrow","Due Diligence","IP"],sr:"LinkedIn"},
{n:"Yagaan",c:"Startup Cyber",v:"Rennes",t:"TPE",s:"yagaan.com",sp:["SAST","Code Review","DevSecOps"],sr:"LinkedIn"},
{n:"Sqreen (Datadog)",c:"Startup Cyber",v:"Paris",t:"PME",s:"sqreen.com",sp:["RASP","AppSec","DevSecOps"],sr:"LinkedIn"},
{n:"Bearer",c:"Startup Cyber",v:"Paris",t:"TPE",s:"bearer.com",sp:["Data Flow","Privacy","DevSecOps"],sr:"LinkedIn"},
{n:"Mithril Security",c:"Startup Cyber",v:"Paris",t:"TPE",s:"mithrilsecurity.io",sp:["AI Security","Confidential Computing"],sr:"LinkedIn, WTTJ"},
{n:"OverSOC",c:"Startup Cyber",v:"Paris",t:"TPE",s:"oversoc.com",sp:["Attack Surface","Visibility","3D Mapping"],sr:"LinkedIn, WTTJ"},
{n:"Ceeyu",c:"Startup Cyber",v:"Paris",t:"TPE",s:"ceeyu.io",sp:["Third Party Risk","EASM"],sr:"LinkedIn"},
{n:"Hackuity",c:"Startup Cyber",v:"Lyon",t:"TPE",s:"hackuity.io",sp:["Vulnerability Management","Risk-based"],sr:"LinkedIn, WTTJ"},
{n:"Cybi",c:"Startup Cyber",v:"Rennes",t:"TPE",s:"music.cybi.fr",sp:["Attack Graph","Risk","Automation"],sr:"LinkedIn"},
{n:"TrackFlaw",c:"Startup Cyber",v:"Paris",t:"TPE",s:"music.trackflaw.com",sp:["Pentest","Vulnerability","SaaS"],sr:"LinkedIn"},
{n:"Letsencrypt FR / Cert-IST",c:"Pure Player Cyber",v:"Toulouse",t:"PME",s:"cert-ist.com",sp:["CERT","Vulnerability Watch","Incident"],sr:"LinkedIn"},
{n:"Lexsi (Orange Cyber)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"orangecyberdefense.com",sp:["CERT","Forensics","CTI"],sr:"LinkedIn"},
{n:"Ceis (Avisa Partners)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"ceis.eu",sp:["CTI","Stratégie","Veille"],sr:"LinkedIn"},
{n:"Signal-Spam",c:"Startup Cyber",v:"Paris",t:"TPE",s:"signal-spam.fr",sp:["Anti-spam","Email Security"],sr:"LinkedIn"},
{n:"Altospam",c:"Éditeur / Solutions",v:"Toulouse",t:"PME",s:"altospam.com",sp:["Email Security","Anti-spam","Anti-phishing"],sr:"LinkedIn"},
];
