// Entreprises Cybersécurité France - Partie 2 (101-200)
const DATA_PART2 = [
{n:"Sentryo (Cisco)",c:"Startup Cyber",v:"Lyon",t:"PME",s:"sentryo.net",sp:["OT Security","ICS","Network"],sr:"LinkedIn"},
{n:"Tanium France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"tanium.com",sp:["Endpoint Management","Visibility"],sr:"LinkedIn"},
{n:"CyberVadis",c:"Startup Cyber",v:"Paris",t:"PME",s:"cybervadis.com",sp:["Third Party Risk","GRC","Assessment"],sr:"WTTJ"},
{n:"Citalid",c:"Startup Cyber",v:"Paris",t:"TPE",s:"citalid.com",sp:["Cyber Risk Quantification","CTI"],sr:"LinkedIn, WTTJ"},
{n:"Anozr Way",c:"Startup Cyber",v:"Rennes",t:"TPE",s:"anozrway.com",sp:["Human Risk","OSINT","Awareness"],sr:"LinkedIn, WTTJ"},
{n:"Patrowl",c:"Startup Cyber",v:"Paris",t:"TPE",s:"patrowl.io",sp:["EASM","Pentest Automation","Vulnerability"],sr:"LinkedIn, WTTJ"},
{n:"GitGuardian",c:"Startup Cyber",v:"Paris",t:"PME",s:"gitguardian.com",sp:["Secrets Detection","DevSecOps","Code Security"],sr:"LinkedIn, WTTJ"},
{n:"Escape",c:"Startup Cyber",v:"Paris",t:"TPE",s:"escape.tech",sp:["API Security","GraphQL","DevSecOps"],sr:"LinkedIn, WTTJ"},
{n:"Riot (ex-Mantra)",c:"Startup Cyber",v:"Paris",t:"TPE",s:"tryriot.com",sp:["Awareness","Phishing Simulation"],sr:"LinkedIn, WTTJ"},
{n:"Lybero.net",c:"Startup Cyber",v:"Paris",t:"TPE",s:"lybero.net",sp:["Chiffrement","Privacy","Open Source"],sr:"LinkedIn"},
{n:"Tixeo",c:"Éditeur / Solutions",v:"Montpellier",t:"PME",s:"tixeo.com",sp:["Visio sécurisée","Chiffrement"],sr:"LinkedIn"},
{n:"TheGreenBow",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"thegreenbow.com",sp:["VPN","Chiffrement","Endpoint"],sr:"LinkedIn"},
{n:"Prim'X Technologies",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"primx.eu",sp:["Chiffrement","Data Protection"],sr:"LinkedIn"},
{n:"Ercom (Thales)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"ercom.com",sp:["Mobile Security","Communications"],sr:"LinkedIn"},
{n:"Idecsi",c:"Startup Cyber",v:"Paris",t:"TPE",s:"idecsi.com",sp:["M365 Security","Data Protection"],sr:"LinkedIn, WTTJ"},
{n:"Nybble Security",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"nybble-security.com",sp:["Pentest","Red Team","Web"],sr:"LinkedIn"},
{n:"DenyAll (Rohde & Schwarz)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"denyall.com",sp:["WAF","API Security"],sr:"LinkedIn"},
{n:"BeSOFT",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"besoft.fr",sp:["Consulting","IAM","Intégration"],sr:"LinkedIn"},
{n:"SII Group",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"sii-group.com",sp:["Consulting","Testing","Cyber"],sr:"LinkedIn, Indeed"},
{n:"Aubay",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"aubay.com",sp:["Consulting","Finance","Sécurité"],sr:"LinkedIn, Indeed"},
{n:"Consort NT",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"consort-nt.com",sp:["Infra","Sécurité","Cloud"],sr:"LinkedIn"},
{n:"Open (Groupe)",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"open.global",sp:["Consulting","Cloud","Sécurité"],sr:"LinkedIn"},
{n:"Linkbynet (Accenture)",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"linkbynet.com",sp:["Cloud Security","MSSP","SOC"],sr:"LinkedIn"},
{n:"Securinfor",c:"Intégrateur / MSSP",v:"Toulouse",t:"PME",s:"securinfor.com",sp:["Intégration","SOC","Firewall"],sr:"LinkedIn"},
{n:"Proofpoint France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"proofpoint.com",sp:["Email Security","DLP","Awareness"],sr:"LinkedIn, Indeed"},
{n:"Fortinet France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"fortinet.com",sp:["Firewall","SD-WAN","SASE"],sr:"LinkedIn, Indeed"},
{n:"Palo Alto Networks France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"paloaltonetworks.com",sp:["Firewall","XDR","Cloud Security"],sr:"LinkedIn, Indeed"},
{n:"CrowdStrike France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"crowdstrike.com",sp:["EDR","XDR","Threat Intel"],sr:"LinkedIn"},
{n:"Trend Micro France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"trendmicro.com",sp:["Endpoint","Cloud Security","XDR"],sr:"LinkedIn"},
{n:"Check Point France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"checkpoint.com",sp:["Firewall","Cloud Security","Endpoint"],sr:"LinkedIn, Indeed"},
{n:"Qualys France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"qualys.com",sp:["Vulnerability Management","Cloud"],sr:"LinkedIn"},
{n:"Varonis France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"varonis.com",sp:["Data Security","IAM","UEBA"],sr:"LinkedIn"},
{n:"Sailpoint France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"sailpoint.com",sp:["IAM","Governance","Identity"],sr:"LinkedIn"},
{n:"CyberArk France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"cyberark.com",sp:["PAM","Privileged Access","IAM"],sr:"LinkedIn, Indeed"},
{n:"Splunk France (Cisco)",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"splunk.com",sp:["SIEM","Observability","Security Analytics"],sr:"LinkedIn"},
{n:"IBM Security France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"ibm.com",sp:["SIEM","SOAR","IAM","Consulting"],sr:"LinkedIn, Indeed"},
{n:"Microsoft France (Security)",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"microsoft.com",sp:["Cloud Security","Identity","XDR"],sr:"LinkedIn, Indeed"},
{n:"Darktrace France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"darktrace.com",sp:["NDR","IA","Autonomous Response"],sr:"LinkedIn"},
{n:"Rapid7 France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"rapid7.com",sp:["Vulnerability","Detection","SIEM"],sr:"LinkedIn"},
{n:"Tenable France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"tenable.com",sp:["Vulnerability","Exposure","OT"],sr:"LinkedIn"},
{n:"Vectra AI France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"vectra.ai",sp:["NDR","IA","XDR"],sr:"LinkedIn"},
{n:"SentinelOne France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"sentinelone.com",sp:["EDR","XDR","IA"],sr:"LinkedIn"},
{n:"WithSecure France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"withsecure.com",sp:["Endpoint","Consulting","Detection"],sr:"LinkedIn"},
{n:"Zscaler France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"zscaler.com",sp:["SASE","Zero Trust","Cloud Security"],sr:"LinkedIn"},
{n:"Netskope France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"netskope.com",sp:["CASB","SASE","DLP"],sr:"LinkedIn"},
{n:"Wiz France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"wiz.io",sp:["Cloud Security","CNAPP"],sr:"LinkedIn"},
{n:"Lacework France (Fortinet)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"lacework.com",sp:["Cloud Security","Runtime"],sr:"LinkedIn"},
{n:"Snyk France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"snyk.io",sp:["DevSecOps","SCA","Container Security"],sr:"LinkedIn"},
{n:"Sonar France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"sonarsource.com",sp:["Code Quality","SAST","DevSecOps"],sr:"LinkedIn, WTTJ"},
{n:"Veracode France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"veracode.com",sp:["SAST","DAST","SCA"],sr:"LinkedIn"},
{n:"Sophos France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"sophos.com",sp:["Endpoint","Firewall","MDR"],sr:"LinkedIn"},
{n:"ESET France",c:"Éditeur / Solutions",v:"Lyon",t:"PME",s:"eset.com",sp:["Endpoint","Antivirus","Detection"],sr:"LinkedIn"},
{n:"Bitdefender France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"bitdefender.com",sp:["Endpoint","GravityZone","MDR"],sr:"LinkedIn"},
{n:"Kaspersky France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"kaspersky.fr",sp:["Endpoint","Threat Intel","EDR"],sr:"LinkedIn"},
{n:"Exclusive Networks",c:"Intégrateur / MSSP",v:"Paris",t:"ETI",s:"exclusive-networks.com",sp:["Distribution","VAD","Cybersecurity"],sr:"LinkedIn, Indeed"},
{n:"Hermitage Solutions",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"hermitage-solutions.com",sp:["Intégration","Sécurité réseau"],sr:"LinkedIn"},
{n:"Jaguar Network (Free Pro)",c:"Telecom / Cloud",v:"Marseille",t:"PME",s:"jaguar-network.com",sp:["Hébergement","Cloud","DDoS"],sr:"LinkedIn"},
{n:"Outscale (Dassault)",c:"Telecom / Cloud",v:"Paris",t:"PME",s:"outscale.com",sp:["Cloud souverain","SecNumCloud"],sr:"LinkedIn, WTTJ"},
{n:"NumSpot",c:"Telecom / Cloud",v:"Paris",t:"PME",s:"numspot.com",sp:["Cloud souverain","Sécurité"],sr:"LinkedIn, WTTJ"},
{n:"S3NS (Thales/Google)",c:"Telecom / Cloud",v:"Paris",t:"PME",s:"s3ns.io",sp:["Cloud souverain","Compliance"],sr:"LinkedIn"},
{n:"Bleu (Capgemini/Orange)",c:"Telecom / Cloud",v:"Paris",t:"PME",s:"bleu.fr",sp:["Cloud souverain","Azure","Compliance"],sr:"LinkedIn"},
{n:"Olvid",c:"Startup Cyber",v:"Paris",t:"TPE",s:"olvid.io",sp:["Messagerie sécurisée","Chiffrement"],sr:"LinkedIn, WTTJ"},
{n:"Dust Mobile",c:"Startup Cyber",v:"Paris",t:"TPE",s:"music.dustmobile.com",sp:["Mobile Security","Telecom Security"],sr:"LinkedIn"},
{n:"CyberTrust",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"cybertrust.fr",sp:["Consulting","GRC","Audit"],sr:"LinkedIn"},
{n:"Abicom",c:"Intégrateur / MSSP",v:"Strasbourg",t:"PME",s:"abicom.fr",sp:["Intégration","Firewall","SOC"],sr:"LinkedIn"},
{n:"SNS Security",c:"Intégrateur / MSSP",v:"Montpellier",t:"PME",s:"sns-security.fr",sp:["MSSP","SOC","Fortinet"],sr:"LinkedIn"},
{n:"Certilience",c:"Pure Player Cyber",v:"Lyon",t:"PME",s:"certilience.fr",sp:["SOC","Audit","Pentest"],sr:"LinkedIn"},
{n:"Novalys",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"novalys.fr",sp:["Consulting","IAM","GRC"],sr:"LinkedIn"},
{n:"Oppida",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"oppida.fr",sp:["Évaluation","Certification","CESTI"],sr:"LinkedIn"},
{n:"Serma NES",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"serma.com",sp:["Hardware Security","Evaluation"],sr:"LinkedIn"},
{n:"Thinkcode (Groupe)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"thinkcode.fr",sp:["Consulting","DevSecOps","Cloud"],sr:"LinkedIn"},
{n:"Cyblex Consulting",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"cyblex-consulting.com",sp:["OT Security","Consulting","Industrie"],sr:"LinkedIn"},
{n:"Seclab",c:"Startup Cyber",v:"Montpellier",t:"TPE",s:"music.seclab-security.com",sp:["OT Security","Network Diode"],sr:"LinkedIn"},
{n:"Nozomi Networks France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"nozominetworks.com",sp:["OT Security","ICS","Visibility"],sr:"LinkedIn"},
{n:"Claroty France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"claroty.com",sp:["OT Security","XIoT","Visibility"],sr:"LinkedIn"},
{n:"Dragos France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"dragos.com",sp:["OT Security","ICS","Threat Intel"],sr:"LinkedIn"},
{n:"Radiflow France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"radiflow.com",sp:["OT Security","Risk","IDS"],sr:"LinkedIn"},
{n:"Cyber Test Systems",c:"Startup Cyber",v:"Bordeaux",t:"TPE",s:"music.cybertestsystems.com",sp:["Automotive Security","Testing"],sr:"LinkedIn"},
{n:"Prove & Run",c:"Startup Cyber",v:"Paris",t:"TPE",s:"music.provenrun.com",sp:["Trusted OS","Firmware","IoT"],sr:"LinkedIn"},
{n:"Ubik Ingénierie",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"ubik-ingenierie.com",sp:["PASSI","Audit","Consulting"],sr:"LinkedIn"},
{n:"Ziwit (HTTPCS)",c:"Pure Player Cyber",v:"Montpellier",t:"PME",s:"ziwit.com",sp:["Pentest","Scanner","PASSI"],sr:"LinkedIn"},
{n:"Olfeo",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"olfeo.com",sp:["Web Filtering","Proxy","Trust-based"],sr:"LinkedIn"},
{n:"Tenacy",c:"Startup Cyber",v:"Lyon",t:"TPE",s:"tenacy.io",sp:["GRC","Cyber Posture","Compliance"],sr:"LinkedIn, WTTJ"},
{n:"Axians (Vinci Energies)",c:"Intégrateur / MSSP",v:"Paris",t:"ETI",s:"axians.com",sp:["SOC","Intégration","Network"],sr:"LinkedIn, Indeed"},
{n:"Ametra (Cyber)",c:"ESN / Consulting IT",v:"Toulouse",t:"PME",s:"music.ametra.fr",sp:["Défense","OT","Consulting"],sr:"LinkedIn"},
{n:"BearingPoint (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"ETI",s:"bearingpoint.com",sp:["Consulting","GRC","Strategy"],sr:"LinkedIn, Indeed"},
{n:"Mazars (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"ETI",s:"forvismazars.com",sp:["Audit","GRC","Consulting"],sr:"LinkedIn, Indeed"},
{n:"Grant Thornton (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"ETI",s:"grantthornton.fr",sp:["Audit","GRC","Consulting"],sr:"LinkedIn"},
];
