// Entreprises Cybersécurité France - Partie 5 (401-530)
const DATA_PART5 = [
{n:"Nanotrust",c:"Startup Cyber",v:"Paris",t:"TPE",s:"nanotrust.io",sp:["Blockchain","Trust","Identity"],sr:"LinkedIn"},
{n:"Scassi",c:"Pure Player Cyber",v:"Toulouse",t:"PME",s:"scassi.com",sp:["Consulting","Audit","GRC","Formation"],sr:"LinkedIn"},
{n:"Sogeti (Testing Security)",c:"ESN / Consulting IT",v:"Lyon",t:"GE",s:"sogeti.com",sp:["Security Testing","IAST","QA"],sr:"LinkedIn"},
{n:"Hub One (ADP)",c:"Telecom / Cloud",v:"Paris",t:"ETI",s:"hubone.fr",sp:["MSSP","SOC","WiFi Security"],sr:"LinkedIn"},
{n:"Nextira One / Convergence",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"music.nextiraone.com",sp:["Network Security","Intégration"],sr:"LinkedIn"},
{n:"Spie ICS",c:"Intégrateur / MSSP",v:"Paris",t:"ETI",s:"spie-ics.com",sp:["Intégration","MSSP","Cloud"],sr:"LinkedIn, Indeed"},
{n:"Kyndryl France (Security)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"kyndryl.com",sp:["MSSP","SOC","Infra Security"],sr:"LinkedIn"},
{n:"T-Systems France (Security)",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"t-systems.com",sp:["MSSP","SOC","Cloud Security"],sr:"LinkedIn"},
{n:"Prodware (Security)",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"prodware.fr",sp:["Microsoft Security","Cloud","ERP"],sr:"LinkedIn"},
{n:"Smile (Security)",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"smile.eu",sp:["Open Source Security","DevSecOps"],sr:"LinkedIn"},
{n:"Octo Technology (Cyber)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"octo.com",sp:["DevSecOps","Cloud","Architecture"],sr:"LinkedIn, WTTJ"},
{n:"Zenika (Security)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"zenika.com",sp:["DevSecOps","Cloud","Consulting"],sr:"LinkedIn, WTTJ"},
{n:"WeScale",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"wescale.fr",sp:["Cloud Security","DevOps","AWS"],sr:"LinkedIn, WTTJ"},
{n:"D2SI / Devoteam (Cloud Sec)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"devoteam.com",sp:["AWS Security","Cloud","DevOps"],sr:"LinkedIn"},
{n:"Padok",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"padok.fr",sp:["DevSecOps","Kubernetes","Cloud"],sr:"LinkedIn, WTTJ"},
{n:"Ippon Technologies (Security)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"ippon.fr",sp:["Cloud Security","DevSecOps","Java"],sr:"LinkedIn, WTTJ"},
{n:"Theodo (Security)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"theodo.com",sp:["AppSec","DevSecOps","Agile"],sr:"LinkedIn, WTTJ"},
{n:"Xebia France (Security)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"xebia.fr",sp:["Cloud Security","DevSecOps"],sr:"LinkedIn, WTTJ"},
{n:"Objvly / BoondManager (Cyber)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"music.objvly.com",sp:["Consulting","GRC"],sr:"LinkedIn"},
{n:"mc2i (Cyber)",c:"ESN / Consulting IT",v:"Paris",t:"PME",s:"mc2i.fr",sp:["Consulting","GRC","Transformation"],sr:"LinkedIn, WTTJ"},
{n:"Sia Partners (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"ETI",s:"sia-partners.com",sp:["Consulting","GRC","Strategy"],sr:"LinkedIn, WTTJ"},
{n:"Chappuis Halder (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"PME",s:"chappuishalder.com",sp:["FinSec","GRC","Consulting"],sr:"LinkedIn"},
{n:"Ailancy (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"PME",s:"ailancy.com",sp:["FinSec","GRC","Compliance"],sr:"LinkedIn"},
{n:"Harwell Management (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"PME",s:"harwell-management.com",sp:["GRC","Consulting","Privacy"],sr:"LinkedIn"},
{n:"TNP Consultants (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"PME",s:"tnp.fr",sp:["GRC","Consulting","Risk"],sr:"LinkedIn"},
{n:"HeadMind Partners (Cyber)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"PME",s:"headmind.com",sp:["Consulting","GRC","IAM","Data"],sr:"LinkedIn, WTTJ"},
{n:"Meanquest",c:"Intégrateur / MSSP",v:"Nantes",t:"PME",s:"meanquest.com",sp:["SOC","MSSP","Intégration"],sr:"LinkedIn"},
{n:"Adista (Security)",c:"Telecom / Cloud",v:"Nancy",t:"PME",s:"adista.fr",sp:["MSSP","SOC","Cloud"],sr:"LinkedIn"},
{n:"Foliateam (Security)",c:"Telecom / Cloud",v:"Lyon",t:"PME",s:"foliateam.com",sp:["Telecom","Security","Cloud"],sr:"LinkedIn"},
{n:"Bouygues Telecom Entreprises",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"bouyguestelecom.fr",sp:["MSSP","SOC","Network"],sr:"LinkedIn"},
{n:"Colt Technology (Security)",c:"Telecom / Cloud",v:"Paris",t:"ETI",s:"colt.net",sp:["Network Security","DDoS","SD-WAN"],sr:"LinkedIn"},
{n:"GTT France (Security)",c:"Telecom / Cloud",v:"Paris",t:"ETI",s:"gtt.net",sp:["Network Security","SD-WAN","DDoS"],sr:"LinkedIn"},
{n:"Wipro CyberSecurite France",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"wipro.com",sp:["MSSP","Consulting","Cloud"],sr:"LinkedIn"},
{n:"Avanade France (Security)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"avanade.com",sp:["Microsoft Security","Cloud","IAM"],sr:"LinkedIn"},
{n:"Reply France (Cyber)",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"reply.com",sp:["Consulting","Cloud","AppSec"],sr:"LinkedIn"},
{n:"Computacenter France",c:"Intégrateur / MSSP",v:"Paris",t:"ETI",s:"computacenter.com",sp:["Intégration","MSSP","Workplace"],sr:"LinkedIn"},
{n:"SCC France (Security)",c:"Intégrateur / MSSP",v:"Paris",t:"ETI",s:"scc.com",sp:["Intégration","Cloud","Security"],sr:"LinkedIn"},
{n:"Insight France (Security)",c:"Intégrateur / MSSP",v:"Paris",t:"ETI",s:"insight.com",sp:["Cloud Security","Intégration"],sr:"LinkedIn"},
{n:"Metsys",c:"Intégrateur / MSSP",v:"Paris",t:"PME",s:"metsys.fr",sp:["Microsoft Security","IAM","Intune"],sr:"LinkedIn, WTTJ"},
{n:"ITS Group (Security)",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"music.itsgroup.com",sp:["Consulting","Cloud","Sécurité"],sr:"LinkedIn"},
{n:"Groupe Hisi",c:"Intégrateur / MSSP",v:"Lyon",t:"PME",s:"music.hisi.fr",sp:["Intégration","SOC","Cloud"],sr:"LinkedIn"},
{n:"FrameIP (Security)",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"frameip.com",sp:["Pentest","Formation","Audit"],sr:"LinkedIn"},
{n:"Hacknowledge (Cyber)",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"music.hacknowledge.com",sp:["SOC","MDR","Detection"],sr:"LinkedIn"},
{n:"CyberAngel",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"cybelangel.com",sp:["EASM","Data Leak","Dark Web"],sr:"LinkedIn"},
{n:"DarkTrace Antigena France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"darktrace.com",sp:["IA","NDR","Autonomous"],sr:"LinkedIn"},
{n:"OnCloud (Security)",c:"Telecom / Cloud",v:"Paris",t:"PME",s:"music.oncloud.fr",sp:["Cloud","MSSP","Backup"],sr:"LinkedIn"},
{n:"OpenTrust (Docaposte)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"docaposte.com",sp:["PKI","Certificate","Trust"],sr:"LinkedIn"},
{n:"Ercom Citadel (Thales)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"ercom.com",sp:["Secure Mobile","Encryption"],sr:"LinkedIn"},
{n:"Tanker (io)",c:"Startup Cyber",v:"Paris",t:"TPE",s:"tanker.io",sp:["E2E Encryption","Privacy","SDK"],sr:"LinkedIn, WTTJ"},
{n:"Seald",c:"Startup Cyber",v:"Paris",t:"TPE",s:"seald.io",sp:["Encryption SDK","Data Protection"],sr:"LinkedIn, WTTJ"},
{n:"Snowflake France (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"snowflake.com",sp:["Data Security","Cloud","Governance"],sr:"LinkedIn"},
{n:"HashiCorp France (Security)",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"hashicorp.com",sp:["Vault","Secrets","Zero Trust"],sr:"LinkedIn"},
{n:"GitLab France (Security)",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"gitlab.com",sp:["DevSecOps","SAST","DAST"],sr:"LinkedIn"},
{n:"Sonatype France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"sonatype.com",sp:["SCA","Supply Chain Security"],sr:"LinkedIn"},
{n:"Checkmarx France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"checkmarx.com",sp:["SAST","SCA","AppSec"],sr:"LinkedIn"},
{n:"HCLTech France (Security)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"hcltech.com",sp:["MSSP","SOC","Cloud"],sr:"LinkedIn"},
{n:"Tech Mahindra France",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"techmahindra.com",sp:["MSSP","5G Security","Cloud"],sr:"LinkedIn"},
{n:"Kudelski Security France",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"kudelskisecurity.com",sp:["MSSP","Consulting","Blockchain"],sr:"LinkedIn"},
{n:"SecureLink France (Orange)",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"orangecyberdefense.com",sp:["MSSP","SOC","Pentest"],sr:"LinkedIn"},
{n:"Binary Security",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"music.binary-security.fr",sp:["Pentest","Red Team","Audit"],sr:"LinkedIn"},
{n:"Ambionics Security",c:"Pure Player Cyber",v:"Lyon",t:"TPE",s:"music.ambionics.io",sp:["Pentest","Web","Research"],sr:"LinkedIn"},
{n:"Wavely (SOC)",c:"Pure Player Cyber",v:"Toulouse",t:"PME",s:"itrust.fr",sp:["SOC managé","PME","SIEM"],sr:"LinkedIn"},
{n:"SoSafe France",c:"Startup Cyber",v:"Paris",t:"PME",s:"sosafe-awareness.com",sp:["Awareness","Phishing Simulation"],sr:"LinkedIn, WTTJ"},
{n:"KnowBe4 France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"knowbe4.com",sp:["Awareness","Phishing","Training"],sr:"LinkedIn"},
{n:"Cofense France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"cofense.com",sp:["Phishing","Email Security","IR"],sr:"LinkedIn"},
{n:"PhishMe France (Cofense)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"cofense.com",sp:["Phishing Simulation","Awareness"],sr:"LinkedIn"},
{n:"Proofpoint France (Awareness)",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"proofpoint.com",sp:["Awareness","Phishing","DLP"],sr:"LinkedIn"},
{n:"Terranova France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"terranovasecurity.com",sp:["Awareness","Training","Phishing"],sr:"LinkedIn"},
{n:"CyberUniversity / DataScientest",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"cyberuniversity.com",sp:["Formation","Certification","Training"],sr:"LinkedIn, WTTJ"},
{n:"Oteria Cyber School",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"oteria.fr",sp:["Formation","École","Alternance"],sr:"LinkedIn, WTTJ"},
{n:"Jedha (Cyber)",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"jedha.co",sp:["Formation","Bootcamp","Cyber"],sr:"LinkedIn"},
{n:"Guardia Cybersecurity School",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"music.guardia.school",sp:["Formation","École"],sr:"LinkedIn"},
{n:"M&A Cybersec (Mazars)",c:"Big4 / Cabinet Conseil",v:"Paris",t:"ETI",s:"forvismazars.com",sp:["Due Diligence","M&A","GRC"],sr:"LinkedIn"},
{n:"Alcyconie",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"alcyconie.com",sp:["Crisis Management","Communication","CERT"],sr:"LinkedIn"},
{n:"Dattak",c:"Startup Cyber",v:"Paris",t:"TPE",s:"dattak.fr",sp:["Cyber Insurance","Risk","PME"],sr:"LinkedIn, WTTJ"},
{n:"Stoïk",c:"Startup Cyber",v:"Paris",t:"TPE",s:"stoik.io",sp:["Cyber Insurance","Risk","PME"],sr:"LinkedIn, WTTJ"},
{n:"Coalition France",c:"Startup Cyber",v:"Paris",t:"PME",s:"coalitioninc.com",sp:["Cyber Insurance","Risk"],sr:"LinkedIn"},
{n:"Beazley France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"beazley.com",sp:["Cyber Insurance","Claims"],sr:"LinkedIn"},
{n:"AIG France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"aig.com",sp:["Cyber Insurance","Risk"],sr:"LinkedIn"},
{n:"Hiscox France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"hiscox.fr",sp:["Cyber Insurance","PME"],sr:"LinkedIn"},
{n:"NBS System",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"nbs-system.com",sp:["Hébergement sécurisé","WAF","PCI"],sr:"LinkedIn"},
{n:"Claranet France (Hosting Sec)",c:"Telecom / Cloud",v:"Paris",t:"ETI",s:"claranet.fr",sp:["Cloud","Managed Hosting","Security"],sr:"LinkedIn"},
{n:"Ikoula (Security)",c:"Telecom / Cloud",v:"Reims",t:"PME",s:"ikoula.com",sp:["Cloud","Hosting","DDoS"],sr:"LinkedIn"},
{n:"Oceanet Technology",c:"Telecom / Cloud",v:"Nantes",t:"PME",s:"music.oceanet-technology.com",sp:["Hosting","Security","Cloud"],sr:"LinkedIn"},
{n:"Outpost24 France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"outpost24.com",sp:["EASM","Pentest-as-Service","Vulnerability"],sr:"LinkedIn"},
{n:"Invicti France (ex-Netsparker)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"invicti.com",sp:["DAST","Web Security","AppSec"],sr:"LinkedIn"},
{n:"HackerOne France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"hackerone.com",sp:["Bug Bounty","VDP","Pentest"],sr:"LinkedIn"},
{n:"Bugcrowd France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"bugcrowd.com",sp:["Bug Bounty","Pentest","VDP"],sr:"LinkedIn"},
{n:"CyberCité / Netinup (Security)",c:"ESN / Consulting IT",v:"Lyon",t:"PME",s:"music.cybercite.fr",sp:["Web Security","Consulting"],sr:"LinkedIn"},
{n:"Login Sécurité",c:"Pure Player Cyber",v:"Paris",t:"PME",s:"music.login-securite.com",sp:["IAM","Consulting","Intégration"],sr:"LinkedIn"},
{n:"Ilex International",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"ilex-international.com",sp:["IAM","SSO","Access Management"],sr:"LinkedIn"},
{n:"Evidian (Atos/Eviden)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"eviden.com",sp:["IAM","SSO","Federation"],sr:"LinkedIn"},
{n:"Usercube",c:"Startup Cyber",v:"Paris",t:"TPE",s:"usercube.com",sp:["IGA","Identity Governance"],sr:"LinkedIn, WTTJ"},
{n:"Brainwave GRC (Radiant Logic)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"brainwave-grc.com",sp:["IGA","Identity Analytics"],sr:"LinkedIn"},
{n:"Memority",c:"Startup Cyber",v:"Paris",t:"TPE",s:"memority.com",sp:["IAM","Cloud Identity","SaaS"],sr:"LinkedIn, WTTJ"},
{n:"Systancia",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"systancia.com",sp:["PAM","VDI","Zero Trust"],sr:"LinkedIn, WTTJ"},
{n:"OneWave",c:"Startup Cyber",v:"Bordeaux",t:"TPE",s:"music.music.one-music",sp:["Password Manager","Biometrics"],sr:"LinkedIn"},
{n:"Specops Software France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"specopssoft.com",sp:["Password","AD Security"],sr:"LinkedIn"},
{n:"SailPoint France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"sailpoint.com",sp:["IGA","Identity","Governance"],sr:"LinkedIn"},
{n:"Saviynt France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"saviynt.com",sp:["IGA","Cloud IAM","PAM"],sr:"LinkedIn"},
{n:"BeyondTrust France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"beyondtrust.com",sp:["PAM","Endpoint Privilege"],sr:"LinkedIn"},
{n:"One Identity France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"oneidentity.com",sp:["IAM","PAM","IGA"],sr:"LinkedIn"},
{n:"Ping Identity France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"pingidentity.com",sp:["IAM","SSO","CIAM"],sr:"LinkedIn"},
{n:"ForgeRock France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"forgerock.com",sp:["IAM","CIAM","Identity"],sr:"LinkedIn"},
{n:"Transmit Security France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"transmitsecurity.com",sp:["Passwordless","CIAM","Identity"],sr:"LinkedIn"},
{n:"Pentera France (ex-Pcysys)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"pentera.io",sp:["Automated Pentest","BAS"],sr:"LinkedIn"},
{n:"AttackIQ France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"attackiq.com",sp:["BAS","Purple Team","MITRE"],sr:"LinkedIn"},
{n:"SafeBreach France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"safebreach.com",sp:["BAS","Simulation","Validation"],sr:"LinkedIn"},
{n:"Cymulate France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"cymulate.com",sp:["BAS","EASM","Purple Team"],sr:"LinkedIn"},
{n:"XM Cyber France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"xmcyber.com",sp:["Attack Path","Hybrid Security"],sr:"LinkedIn"},
{n:"Randori (IBM) France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"randori.com",sp:["EASM","Attack Surface"],sr:"LinkedIn"},
{n:"CybelAngel (EASM)",c:"Startup Cyber",v:"Paris",t:"PME",s:"cybelangel.com",sp:["EASM","Threat Intel","Data Leak"],sr:"LinkedIn, WTTJ"},
{n:"eShard",c:"Startup Cyber",v:"Bordeaux",t:"TPE",s:"eshard.com",sp:["Side Channel","Hardware Security","Mobile"],sr:"LinkedIn"},
{n:"Seckiot",c:"Startup Cyber",v:"Paris",t:"TPE",s:"seckiot.fr",sp:["OT Security","ICS","Monitoring"],sr:"LinkedIn"},
{n:"Sentryo (ICS Security)",c:"Startup Cyber",v:"Lyon",t:"PME",s:"sentryo.net",sp:["ICS","OT Visibility","Network"],sr:"LinkedIn"},
{n:"Moabi",c:"Startup Cyber",v:"Paris",t:"TPE",s:"music.moabi.com",sp:["Supply Chain","Firmware","Analysis"],sr:"LinkedIn"},
{n:"Glimps (Malware IA)",c:"Startup Cyber",v:"Rennes",t:"TPE",s:"glimps.fr",sp:["Malware","IA","Deep Learning"],sr:"LinkedIn, WTTJ"},
{n:"Tetrane",c:"Startup Cyber",v:"Paris",t:"TPE",s:"tetrane.com",sp:["Binary Analysis","Reverse","R&D"],sr:"LinkedIn"},
{n:"Cyrating",c:"Startup Cyber",v:"Paris",t:"TPE",s:"cyrating.com",sp:["Cyber Rating","Assessment","Risk"],sr:"LinkedIn"},
{n:"Egerie",c:"Startup Cyber",v:"Paris",t:"PME",s:"egerie.eu",sp:["Risk Management","GRC","Quantification"],sr:"LinkedIn, WTTJ"},
{n:"C-Risk",c:"Pure Player Cyber",v:"Paris",t:"TPE",s:"c-risk.com",sp:["Cyber Risk Quantification","FAIR"],sr:"LinkedIn"},
{n:"Cylum",c:"Startup Cyber",v:"Paris",t:"TPE",s:"music.cylum.io",sp:["Supply Chain","Software","SBOM"],sr:"LinkedIn"},
{n:"Luatix (OpenCTI / Filigran)",c:"Startup Cyber",v:"Paris",t:"TPE",s:"filigran.io",sp:["Open Source","CTI","Threat Intel"],sr:"LinkedIn, WTTJ"},
{n:"Beamy (Security)",c:"Startup Cyber",v:"Paris",t:"TPE",s:"beamy.io",sp:["SaaS Management","Shadow IT","Governance"],sr:"LinkedIn, WTTJ"},
{n:"Push Security France",c:"Startup Cyber",v:"Paris",t:"TPE",s:"pushsecurity.com",sp:["Browser Security","SaaS","Identity"],sr:"LinkedIn"},
{n:"Tenable.ad France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"tenable.com",sp:["AD Security","Identity","Exposure"],sr:"LinkedIn"},
{n:"Semperis France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"semperis.com",sp:["AD Security","Recovery","Resilience"],sr:"LinkedIn"},
{n:"Netwrix France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"netwrix.com",sp:["AD Security","Data Security","Audit"],sr:"LinkedIn"},
{n:"ManageEngine France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"manageengine.com",sp:["IAM","SIEM","Endpoint"],sr:"LinkedIn"},
{n:"Nexus Group France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"nexusgroup.com",sp:["PKI","Identity","Smart Cards"],sr:"LinkedIn"},
{n:"Keyfactor France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"keyfactor.com",sp:["PKI","Certificate","Machine Identity"],sr:"LinkedIn"},
{n:"Venafi France (CyberArk)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"venafi.com",sp:["Machine Identity","Certificate","TLS"],sr:"LinkedIn"},
{n:"Entrust France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"entrust.com",sp:["PKI","HSM","Identity","Certificate"],sr:"LinkedIn"},
{n:"Utimaco France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"utimaco.com",sp:["HSM","Encryption","Key Management"],sr:"LinkedIn"},
{n:"Thales HSM (payShield/Luna)",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"thalesgroup.com",sp:["HSM","Payment Security","PKI"],sr:"LinkedIn"},
{n:"Atos HSM / Bull",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"eviden.com",sp:["HSM","Trustway","Sovereignty"],sr:"LinkedIn"},
];
