// Entreprises Cybersécurité France - Partie 3 (201-300)
const DATA_PART3 = [
{n:"Thales DIS (Digital Identity & Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"thalesgroup.com",sp:["Identity","Smart Cards","PKI"],sr:"LinkedIn, Indeed"},
{n:"Idemia",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"idemia.com",sp:["Identity","Biometrics","Security"],sr:"LinkedIn, Indeed"},
{n:"Gemalto (Thales)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"thalesgroup.com",sp:["PKI","Smart Cards","Identity"],sr:"LinkedIn"},
{n:"IN Groupe",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"music.ingroupe.com",sp:["Identity","Sécurité documentaire"],sr:"LinkedIn"},
{n:"Worldline (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"worldline.com",sp:["Payment Security","Fraud","PCI"],sr:"LinkedIn, Indeed"},
{n:"Ingenico (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"ingenico.com",sp:["Payment Security","Embedded"],sr:"LinkedIn"},
{n:"Criteo (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"criteo.com",sp:["AppSec","Cloud Security","Privacy"],sr:"LinkedIn, WTTJ"},
{n:"Deezer (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"ETI",s:"deezer.com",sp:["AppSec","Cloud","Privacy"],sr:"LinkedIn, WTTJ"},
{n:"Dailymotion (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"PME",s:"dailymotion.com",sp:["AppSec","Cloud","Privacy"],sr:"LinkedIn"},
{n:"OVHcloud Security",c:"Telecom / Cloud",v:"Roubaix",t:"ETI",s:"ovhcloud.com",sp:["Cloud Security","SOC","Anti-DDoS"],sr:"LinkedIn, WTTJ"},
{n:"Ubisoft (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"ubisoft.com",sp:["Game Security","AppSec","Cloud"],sr:"LinkedIn"},
{n:"Verizon France (Cyber)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"verizon.com",sp:["MSSP","Incident Response","MDR"],sr:"LinkedIn"},
{n:"BT France (Security)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"bt.com",sp:["MSSP","SOC","Network Security"],sr:"LinkedIn"},
{n:"Wipro France (Cyber)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"wipro.com",sp:["MSSP","SOC","Consulting"],sr:"LinkedIn"},
{n:"Tata Consultancy France",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"tcs.com",sp:["Consulting","SOC","Cloud Security"],sr:"LinkedIn"},
{n:"Infosys France (Cyber)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"infosys.com",sp:["Consulting","MSSP","Cloud"],sr:"LinkedIn"},
{n:"NTT Data France (Security)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"nttdata.com",sp:["MSSP","SOC","Consulting"],sr:"LinkedIn"},
{n:"DXC Technology France",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"dxc.com",sp:["MSSP","Infra Security","Cloud"],sr:"LinkedIn"},
{n:"Unisys France (Security)",c:"ESN / Consulting IT",v:"Paris",t:"ETI",s:"unisys.com",sp:["Zero Trust","Consulting","MSSP"],sr:"LinkedIn"},
{n:"Publicis Sapient (Cyber)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"publicissapient.com",sp:["AppSec","Cloud","Consulting"],sr:"LinkedIn"},
{n:"SNCF (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"sncf.com",sp:["OT Security","SOC","GRC"],sr:"LinkedIn, Indeed"},
{n:"RATP (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"ratp.fr",sp:["OT Security","SOC","SCADA"],sr:"LinkedIn"},
{n:"Veolia (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"veolia.com",sp:["OT Security","SCADA","SOC"],sr:"LinkedIn, Indeed"},
{n:"Suez (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"suez.com",sp:["OT Security","Water SCADA"],sr:"LinkedIn"},
{n:"Air France-KLM (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"airfranceklm.com",sp:["SOC","Cloud Security","Fraud"],sr:"LinkedIn, Indeed"},
{n:"Carrefour (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"carrefour.com",sp:["Retail Security","SOC","PCI"],sr:"LinkedIn, Indeed"},
{n:"Leclerc (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"e-leclerc.com",sp:["Retail Security","SOC"],sr:"LinkedIn"},
{n:"Auchan (Cyber)",c:"Entreprise avec équipe cyber",v:"Lille",t:"GE",s:"auchan.fr",sp:["Retail Security","SOC","PCI"],sr:"LinkedIn"},
{n:"Michelin (Cyber)",c:"Entreprise avec équipe cyber",v:"Clermont-Ferrand",t:"GE",s:"michelin.com",sp:["OT Security","SOC","Cloud"],sr:"LinkedIn"},
{n:"Danone (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"danone.com",sp:["Cloud Security","SOC","GRC"],sr:"LinkedIn"},
{n:"Pernod Ricard (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"pernod-ricard.com",sp:["Cloud Security","IAM"],sr:"LinkedIn"},
{n:"Hermès (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"hermes.com",sp:["SOC","Cloud Security"],sr:"LinkedIn"},
{n:"LVMH (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"lvmh.com",sp:["SOC","IAM","Cloud Security"],sr:"LinkedIn"},
{n:"Kering (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"kering.com",sp:["SOC","Cloud Security"],sr:"LinkedIn"},
{n:"AccorHotels (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"group.accor.com",sp:["SOC","PCI","Cloud Security"],sr:"LinkedIn"},
{n:"Sodexo (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"sodexo.com",sp:["SOC","IAM","Cloud"],sr:"LinkedIn"},
{n:"Vinci (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"vinci.com",sp:["OT Security","SOC","Infra"],sr:"LinkedIn"},
{n:"Bouygues Construction (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"bouygues-construction.com",sp:["OT Security","SOC"],sr:"LinkedIn"},
{n:"Eiffage (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"eiffage.com",sp:["OT Security","SOC"],sr:"LinkedIn"},
{n:"Arkema (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"arkema.com",sp:["OT Security","SCADA","SOC"],sr:"LinkedIn"},
{n:"Air Liquide (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"airliquide.com",sp:["OT Security","SOC","Cloud"],sr:"LinkedIn"},
{n:"Legrand (Cyber)",c:"Entreprise avec équipe cyber",v:"Limoges",t:"GE",s:"legrand.com",sp:["IoT Security","Product Security"],sr:"LinkedIn"},
{n:"Valeo (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"valeo.com",sp:["Automotive Security","OT"],sr:"LinkedIn"},
{n:"Faurecia / Forvia (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"forvia.com",sp:["Automotive Security","OT"],sr:"LinkedIn"},
{n:"Stellantis France (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"stellantis.com",sp:["Automotive Security","OT","SOC"],sr:"LinkedIn"},
{n:"La Poste (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"lapostegroupe.com",sp:["SOC","Identity","Cloud"],sr:"LinkedIn, Indeed"},
{n:"Orange (Interne Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"orange.com",sp:["SOC","Network Security","5G"],sr:"LinkedIn, Indeed"},
{n:"Canal+ (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"canalplus.com",sp:["DRM","Content Security","SOC"],sr:"LinkedIn"},
{n:"TF1 (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"tf1.fr",sp:["Media Security","SOC","Cloud"],sr:"LinkedIn"},
{n:"Vivendi (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"vivendi.com",sp:["SOC","GRC","Cloud"],sr:"LinkedIn"},
{n:"Atos BDS (Big Data & Security)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"atos.net",sp:["HPC","Défense","Cloud souverain"],sr:"LinkedIn"},
{n:"Soteria Lab",c:"Pure Player Cyber",v:"Metz",t:"PME",s:"soterialab.com",sp:["Audit","Pentest","Consulting","SOC"],sr:"LinkedIn"},
{n:"Zyxel France (Security)",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"zyxel.com",sp:["Firewall SMB","VPN","Network"],sr:"LinkedIn"},
{n:"Stormshield (Network)",c:"Éditeur / Solutions",v:"Lille",t:"PME",s:"stormshield.com",sp:["Firewall","Network Security"],sr:"LinkedIn"},
{n:"Rohde & Schwarz Cybersecurity France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"rohde-schwarz.com",sp:["WAF","Network Security","Telecom"],sr:"LinkedIn"},
{n:"NXP France (Security)",c:"Entreprise avec équipe cyber",v:"Grenoble",t:"GE",s:"nxp.com",sp:["Embedded Security","IoT","Chip"],sr:"LinkedIn"},
{n:"STMicroelectronics (Security)",c:"Entreprise avec équipe cyber",v:"Grenoble",t:"GE",s:"st.com",sp:["Embedded Security","Chip","IoT"],sr:"LinkedIn"},
{n:"Ericsson France (Security)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"ericsson.com",sp:["Telecom Security","5G","Network"],sr:"LinkedIn"},
{n:"Nokia France (Security)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"nokia.com",sp:["Telecom Security","5G","Network"],sr:"LinkedIn"},
{n:"Huawei France (Security)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"huawei.com",sp:["Telecom Security","5G","Cloud"],sr:"LinkedIn"},
{n:"Cisco France (Security)",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"cisco.com",sp:["Network Security","XDR","SASE"],sr:"LinkedIn, Indeed"},
{n:"VMware France (Security)",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"vmware.com",sp:["NSX","Carbon Black","Cloud"],sr:"LinkedIn"},
{n:"Mandiant/Google Cloud France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"mandiant.com",sp:["Incident Response","CTI","Detection"],sr:"LinkedIn"},
{n:"AWS France (Security)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"aws.amazon.com",sp:["Cloud Security","IAM","Compliance"],sr:"LinkedIn, Indeed"},
{n:"Google Cloud France (Security)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"cloud.google.com",sp:["Cloud Security","Chronicle","BeyondCorp"],sr:"LinkedIn"},
{n:"Salesforce France (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"salesforce.com",sp:["Cloud Security","Privacy","AppSec"],sr:"LinkedIn"},
{n:"SAP France (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"sap.com",sp:["ERP Security","Cloud","GRC"],sr:"LinkedIn"},
{n:"Oracle France (Security)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"oracle.com",sp:["Cloud Security","Database Security","IAM"],sr:"LinkedIn"},
{n:"ServiceNow France (Security)",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"servicenow.com",sp:["SecOps","Vulnerability","ITSM"],sr:"LinkedIn"},
{n:"Okta France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"okta.com",sp:["IAM","SSO","Zero Trust"],sr:"LinkedIn"},
{n:"OneSpan France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"onespan.com",sp:["Authentication","Signature","Fraud"],sr:"LinkedIn"},
{n:"Yousign",c:"Startup Cyber",v:"Paris",t:"PME",s:"yousign.com",sp:["E-signature","Trust","Compliance"],sr:"LinkedIn, WTTJ"},
{n:"Ubble.ai",c:"Startup Cyber",v:"Paris",t:"TPE",s:"ubble.ai",sp:["Identity Verification","KYC","Fraud"],sr:"LinkedIn, WTTJ"},
{n:"ShareID",c:"Startup Cyber",v:"Paris",t:"TPE",s:"shareid.ai",sp:["Identity","Biometrics","Zero Knowledge"],sr:"LinkedIn, WTTJ"},
{n:"Didomi",c:"Startup Cyber",v:"Paris",t:"PME",s:"didomi.io",sp:["Privacy","Consent","RGPD"],sr:"LinkedIn, WTTJ"},
{n:"Usercentrics France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"usercentrics.com",sp:["Privacy","Consent","Compliance"],sr:"LinkedIn"},
{n:"OneTrust France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"onetrust.com",sp:["Privacy","GRC","Compliance"],sr:"LinkedIn"},
{n:"BigID France",c:"Éditeur / Solutions",v:"Paris",t:"PME",s:"bigid.com",sp:["Data Discovery","Privacy","RGPD"],sr:"LinkedIn"},
{n:"Exodata (ex-Itrop)",c:"Pure Player Cyber",v:"Nice",t:"PME",s:"exodata.fr",sp:["SOC","Pentest","MSSP"],sr:"LinkedIn"},
{n:"CS Group (Cyber)",c:"ESN / Consulting IT",v:"Toulouse",t:"ETI",s:"music.csgroup.eu",sp:["Défense","SOC","OT Security"],sr:"LinkedIn"},
{n:"Berger-Levrault (Cyber)",c:"Éditeur / Solutions",v:"Toulouse",t:"ETI",s:"music.berger-levrault.com",sp:["GRC","Public Sector","Cloud"],sr:"LinkedIn"},
{n:"Bull (Atos)",c:"ESN / Consulting IT",v:"Paris",t:"GE",s:"atos.net",sp:["HPC","Défense","Chiffrement"],sr:"LinkedIn"},
{n:"Coreye (Cyber)",c:"Telecom / Cloud",v:"Paris",t:"PME",s:"coreye.fr",sp:["Cloud souverain","MSSP","Compliance"],sr:"LinkedIn"},
{n:"Trellix France (ex-FireEye/McAfee)",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"trellix.com",sp:["XDR","EDR","Email Security"],sr:"LinkedIn"},
{n:"Broadcom/Symantec France",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"broadcom.com",sp:["DLP","Endpoint","CASB"],sr:"LinkedIn"},
{n:"Mimecast France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"mimecast.com",sp:["Email Security","Awareness"],sr:"LinkedIn"},
{n:"Barracuda France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"barracuda.com",sp:["Email Security","WAF","Backup"],sr:"LinkedIn"},
{n:"F5 France (Security)",c:"Éditeur / Solutions",v:"Paris",t:"GE",s:"f5.com",sp:["WAF","API Security","DDoS"],sr:"LinkedIn"},
{n:"Imperva France",c:"Éditeur / Solutions",v:"Paris",t:"ETI",s:"imperva.com",sp:["WAF","DDoS","Data Security"],sr:"LinkedIn"},
{n:"Cloudflare France",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"cloudflare.com",sp:["CDN","DDoS","Zero Trust","SASE"],sr:"LinkedIn"},
{n:"Akamai France (Security)",c:"Telecom / Cloud",v:"Paris",t:"GE",s:"akamai.com",sp:["DDoS","WAF","Zero Trust"],sr:"LinkedIn"},
{n:"Fastly France (Security)",c:"Telecom / Cloud",v:"Paris",t:"ETI",s:"fastly.com",sp:["WAF","Edge Security","CDN"],sr:"LinkedIn"},
{n:"Thales Alenia Space (Cyber)",c:"Entreprise avec équipe cyber",v:"Toulouse",t:"GE",s:"thalesaleniaspace.com",sp:["Space Security","OT","Satellite"],sr:"LinkedIn"},
{n:"MBDA (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"mbda-systems.com",sp:["Défense","OT Security","Missile"],sr:"LinkedIn"},
{n:"Dassault Aviation (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"dassault-aviation.com",sp:["Défense","OT","Aviation Security"],sr:"LinkedIn"},
{n:"Nexter / KNDS (Cyber)",c:"Entreprise avec équipe cyber",v:"Paris",t:"GE",s:"music.knds.com",sp:["Défense","OT Security"],sr:"LinkedIn"},
];
